name: daily-task-4


on:
  
  push: # push触发
    branches: [ main ]
  workflow_dispatch: # 手动触发
  schedule: # 计划任务触发
    - cron: '*/30 0,17 * * *' # cron表达式，Actions时区是UTC时间，所以要往前推8个小时,如上表示每天9点0分
    

jobs:
  daily-task:
    if: github.event.repository.owner.id == github.event.sender.id

    
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12]
        node-registry: ['https://registry.npmjs.org']

    steps:
    
    # 检出
    - name: Checkout
      uses: actions/checkout@v2

    - name: 运行时间
      run: |
       time=$(curl -s "http://quan.suning.com/getSysTime.do")
       echo -e "当前时间：\n${time}"
      
    # 设置服务器时区为东八区 
    - name: Set time zone
      run: sudo timedatectl set-timezone 'Asia/Shanghai'

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: ${{ matrix.node-registry }}

    # 安装依赖
    - name: Install dependencies
      run: npm install

    # 运行 unicom 签到任务
    - name: 号码186320
     
      env:
        user: ${{secrets.HAOMA186}}
        password: ${{secrets.MM}}
        appid: ${{secrets.APPID2}}
      run: node index.js unicom --user=${user} --password=${password} --appid=${appid} --tryrun
   
    - name: 号码6887
     
      env:
        user: ${{secrets.HAOMA68}}
        password: ${{secrets.MM}}
        appid: ${{secrets.APPID2}}
      run: node index.js unicom --user=${user} --password=${password} --appid=${appid} --tryrun
    
    - name: 号码9332
     
      env:
        user: ${{secrets.HAOMA93}}
        password: ${{secrets.MM2}}
        appid: ${{secrets.APPID2}}
      run: node index.js unicom --user=${user} --password=${password} --appid=${appid} --tryrun
